### ISSUE TITLE
Bluetooth not working logs attached

### ISSUE THREAD

**Issue by fank** [crpalmer/android_device_samsung_mondrianlte#2]
http://teamspeak.fankservercdn.com/Fank/2014-07-07_23.36.zip
I flashed to the latest 2014-07-07 build, and want to valid the bluetooth not working issue (http://forum.xda-developers.com/showthread.php?t=2792574&page=5) which i can confirm that it's broken.

I attached the the log file above i hope youll find the problem.

P.S. i don't need bluetooth :)

**Comment by fank** [comment]
i found in the logcat.log line 7207 - 7211

```
07-07 23:34:46.139 D/BluetoothManagerService(  936): Message: 20
07-07 23:34:46.139 D/BluetoothManagerService(  936): Added callback: android.bluetooth.BluetoothAdapter$2@421fa908:true
07-07 23:34:46.139 D/BluetoothManagerService(  936): Message: 30
07-07 23:34:46.139 D/Tethering(  936): Exception adding default nw to upstreamIfaceTypes: java.lang.NullPointerException
07-07 23:34:46.139 W/ContextImpl(  936): Calling a method in the system process without a qualified user: android.app.ContextImpl.bindService:1607 android.bluetooth.BluetoothPan.doBind:148 android.bluetooth.BluetoothPan.<init>:141 android.bluetooth.BluetoothAdapter.getProfileProxy:1378 android.bluetooth.BluetoothTetheringDataTracker.startMonitoring:116 
```

**Comment by crpalmer** [comment]
Thanks, I took a look at it and I think I should be able to push up a build with it fixed tomorrow.

Can you post a message in the xda thread saying that you send me logs so I can thank you there when it's fixed.  Might help encourage people to actually contribute to the work that they are using...

**Comment by fank** [comment]
Sry i would im fankserver in xda but i need to post some messages before i can post on dev threads .... So ill use github 😀

**Comment by fank** [comment]
Ok bluetooth work, i tried the latested firmware you posted.
