### ISSUE TITLE
Green videos

### ISSUE THREAD

**Issue by fank** [crpalmer/android_device_samsung_mondrianlte#3]
As someone posted in the xda forum, i can validate this issue.
I saw this Problem in following apps
- Google chrome
- Firefox nightly
- Android Browser
- some qr Scanner

But i never saw this Problem in following apps
- vlc beta
- camera

Somebody told this issue depends on the dpi

**Comment by fank** [comment]
Could you change the dpi in a test build and upload it so i can test it?

**Comment by crpalmer** [comment]
I don't see any mention of dpi on xda, where do you see that?

Can you give me a link to a specific video that is doing this?  Do you open it full-screen in landscape or not?  Or does it show green in both?  Any chance of taking a video of what it looks like (is it just green, green accents or is the image overlaid in green?)?

**Comment by fank** [comment]
oh sorry i forgot this info, its only in fullscreen and landscape.
And it happend in 90% so if i open a video in fullscreen its green but after switching between not fullscreen and fullscreen multiple times its shown normal in fullscreen on landscape :P

**Comment by fank** [comment]
http://androidforums.com/droid-support-troubleshooting/45923-getting-green-distorted-display-when-viewing-video.html

**Comment by fank** [comment]
i can't find the link again there were someone who told it depends on the screen dpi, but i don't know

**Comment by crpalmer** [comment]
The DPI (I assume you mean the lcd_density build.prop) shouldn't make any difference when viewing videos in full screen.

Can you give me a link to a specific video that is bad for you?  Everything I try on my sm-t320 is working right but maybe I'm just lucky.

I assume that you are using the 2014-07-08 build?

**Comment by fank** [comment]
yep i use the latest build, ill search a video

**Comment by fank** [comment]
http://teamspeak.fankservercdn.com/Fank/VID-20140123-WA0002.mp4 i used google chrome

**Comment by fank** [comment]
full hq videos like http://teamspeak.fankservercdn.com/ArmA_3_04.16.2014_-_19.26.07.11_1.mp4 works without problem

**Comment by fank** [comment]
lol it is shown as green, but if i take a screenshot the screenshow will show the video (no green)

**Comment by fank** [comment]
Can you reproduce this issue on your sm-t320?

**Comment by crpalmer** [comment]
Yes, thanks!

Using the same source (but different device specific config, code, blobs) I see the problem on a mondrianlte build but not on a mondrianwifi build on my sm-t320.

That sounds like I borked something in the mondrianlte.

Unfotunately, I didn't get any time to look at it yesterday and only have a few more minutes today so I'm not going to have much of a chance to make any progress today.

Thanks for finding the video though!

**Comment by fank** [comment]
Here this will show you the problem with this config (https://github.com/crpalmer/android_device_samsung_mondrianlte/issues/3#issuecomment-48457735) 
http://teamspeak.fankservercdn.com/Fank/IMG_0038.MOV

**Comment by fank** [comment]
Fixed in 20140724 build
