### ISSUE TITLE
No option to move App to SD card

### ISSUE THREAD

**Issue by fank** [crpalmer/android_device_samsung_mondrianlte#4]
I ordered an 128 GB SD card http://geizhals.de/eu/sandisk-ultra-microsdxc-128gb-android-sdsdqua-128g-g46a-a1075065.html but my problem is i don't have any option to move internal downloaded apps to the sd card there is no option.

The sd card works fine, im not sure if this is a "android" fault or not.

**Comment by crpalmer** [comment]
I believe that this is a "blame google".  I think that they removed this support awhile ago.  Definitely not related to our device.
